### ISSUE TITLE
struct/interface naming convention

### ISSUE THREAD

**Issue by kyfujisa** [yahoojapan/athenz-client-sidecar#36]
Change to the following naming convention. Do the same for access token code.
-> RoleTokenService
https://github.com/yahoojapan/athenz-client-sidecar/blob/3ceaeb900f4862d62807cd8bdb15172242236e5e/service/role.go#L44

-> roleTokenService
https://github.com/yahoojapan/athenz-client-sidecar/blob/3ceaeb900f4862d62807cd8bdb15172242236e5e/service/role.go#L51

-> RoleTokenResponse( Imitate this: https://github.com/yahoojapan/athenz-client-sidecar/blob/master/service/role.go#L76 )
https://github.com/yahoojapan/athenz-client-sidecar/blob/3ceaeb900f4862d62807cd8bdb15172242236e5e/service/role.go#L76

**Comment by WindzCUHK** [comment]
Also, `RoleProvider => RoleTokenProvider`
https://github.com/yahoojapan/athenz-client-sidecar/blob/3ceaeb900f4862d62807cd8bdb15172242236e5e/service/role.go#L82

**Comment by WindzCUHK** [comment]
continue in: https://github.com/AthenZ/athenz-client-sidecar/issues/5
